### ISSUE TITLE
Error: object 'residual_variance' not found

### ISSUE THREAD

**Issue by xie186** [BUStools/BUS_notebooks_R#2]
Thanks for the detailed tutorial here: https://bustools.github.io/BUS_notebooks_R/slingshot.html#differential_expression

At section "Differential expression", there was an error say "Error: object 'residual_variance' not found"
Could you please help me regarding this problem? Thanks.

**Comment by lambdamoses** [comment]
The residual variance comes from `SCTransform`; if you used `NormalizeData` and `ScaleData`, then you won't get that column in gene metadata. Also, I'm currently rewriting the differential expression section to use `tradeSeq` rather than dynverse's random forest, though the top HVGs will still be used.

**Comment by xie186** [comment]
Thank you.
