### ISSUE TITLE
Incorrect axes labelling for knee plot in mixture kallisto notebook

### ISSUE THREAD

**Issue by matt-sd-watson** [BUStools/BUS_notebooks_R#5]
I am using some of the code suggested in the following notebook for scRNA gene annotation using kallisto: 

https://bustools.github.io/BUS_notebooks_R/10xv2.html

I noticed that for the barcode ranking knee plot, the axis labels seemed to be switched: 

<img width="745" alt="Screen Shot 2022-01-05 at 3 33 21 PM" src="https://user-images.githubusercontent.com/40243147/148285582-9b3993c0-324b-492a-94c9-566406cbf3dc.png">

I believe that what is depicted is actually the barcode rank on the x-axis, and the UMI/transcript countx on the y-axis, not the other way around as shown in the tutorial. This would be consistent with the rendering of the barcode rank plot in cell ranger by 10x: 

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/summary

**Comment by lambdamoses** [comment]
The two axes are actually switched, and the switching is on purpose, because this way this plot is more generalizable to multi-omics, such as when both the transcriptome and proteome are profiled, or for spliced and unspliced for RNA velocity. So we can have the x axis for UMI count for say the transcriptome, y axis for proteome, and z axis for cell barcode rank.

**Comment by lakigigar** [comment]
For additional explanation see: https://liorpachter.wordpress.com/2019/06/24/rotating-the-knee-plot-and-related-yoga/

**Comment by matt-sd-watson** [comment]
Thank you for the explanation and resources!
